In [3]:
import numpy as np
from main import print_matrix
import main

In [14]:
def calculate_gamma(ei_vec):
    Ne = 18
    N = 10
    gamma = np.zeros((N, N), dtype=np.float64)
    for k in range(int(Ne / 2)):  # go through all orbitals that are occupied!
        for i in range(N):
            for j in range(N):
                if i==0 and j == 0:
                    print(k, i, j, gamma[i, j], ei_vec[i, k] * ei_vec[j, k])
                gamma[i, j] += ei_vec[i, k] * ei_vec[j, k]
    return gamma

In [8]:
obj = main.Householder(10, 18, 8)
obj.calculate_one()

calculation with Ns=10, Ne=18, density=1.8
[[ 0. -1.  0.  0.  0.  0.  0.  0.  0. -1.]
 [-1.  0. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0. -1.]
 [-1.  0.  0.  0.  0.  0.  0.  0. -1.  0.]]
   +0.316228     +0.021242     -0.447214     -0.447214     -0.019868     -0.294186     +0.353568     -0.447214     +0.052214     +0.316228
   +0.316228     -0.245383     -0.361803     -0.138197     +0.418766     -0.229436     -0.369698     +0.361803     -0.303309     -0.316228
   +0.316228     -0.418281     -0.138197     +0.361803     +0.278680     +0.435985     -0.125082     -0.138197     +0.438551     +0.316228
   +0.316228     -0.431410     +0.138197     +0.361803     -0.246532     -0.040018     +0.447003     -0.13819

In [9]:
obj.h

array([[ 0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.],
       [-1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  0., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -1.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -1.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0., -1.],
       [-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.]])

In [10]:
ei_val, ei_vec = np.linalg.eig(obj.h)  # v[:,i] corresponds to eigval w[i]
idx = ei_val.argsort()[::1] # Sorting matrix and vector by ascending order
ei_val = ei_val[idx]
ei_vec = ei_vec[:, idx]


In [15]:
calculate_gamma(ei_vec)

0 0 0 0.0 0.10000000000000028
1 0 0 0.10000000000000028 0.0004512338863838408
2 0 0 0.10045123388638412 0.20000000000000043
3 0 0 0.30045123388638456 0.20000000000000018
4 0 0 0.5004512338863847 0.00039475241407344307
5 0 0 0.5008459863004582 0.08654560035200196
6 0 0 0.5873915866524602 0.12501038742828227
7 0 0 0.7124019740807425 0.19999999999999993
8 0 0 0.9124019740807424 0.0027262561174212674


array([[ 0.91512823,  0.06921725, -0.10220641,  0.08253605, -0.08022394,
         0.09111379, -0.11753138,  0.13692925, -0.11516649,  0.12020366],
       [ 0.06921725,  0.89779359,  0.08253605, -0.08022394,  0.09111379,
        -0.11753138,  0.13692925, -0.11516649,  0.12020366, -0.08487177],
       [-0.10220641,  0.08253605,  0.91977606,  0.09111379, -0.11753138,
         0.13692925, -0.11516649,  0.12020366, -0.08487177,  0.06921725],
       [ 0.08253605, -0.08022394,  0.09111379,  0.88246862,  0.13692925,
        -0.11516649,  0.12020366, -0.08487177,  0.06921725, -0.10220641],
       [-0.08022394,  0.09111379, -0.11753138,  0.13692925,  0.88483351,
         0.12020366, -0.08487177,  0.06921725, -0.10220641,  0.08253605],
       [ 0.09111379, -0.11753138,  0.13692925, -0.11516649,  0.12020366,
         0.91512823,  0.06921725, -0.10220641,  0.08253605, -0.08022394],
       [-0.11753138,  0.13692925, -0.11516649,  0.12020366, -0.08487177,
         0.06921725,  0.89779359,  0.08253605

# Test if ei_vec are really eigenvectors:
I calculated h * vec / ei_val - vec for each eigenvector:

In [16]:
for i in range(len(obj.ei_val)):
    print(i,np.sum(np.square(obj.h @ obj.ei_vec[:, i] / obj.ei_val[i] - obj.ei_vec[:, i])))

0 1.5006846126665342e-30
1 1.5163929787754426e-30
2 7.0026812777919896e-31
3 2.9628506264453236e-30
4 8.693768139585507e-31
5 1.4087214578220437e-30
6 1.6948183510607676e-30
7 1.7179295103934144e-31
8 1.54507729788466e-31
9 2.5976943089895037e-30


They seem to be eigenvectors.
We can also try to see if they are linear combination of ones that are calculated by fortran:

In [17]:
fr = np.loadtxt('ei_vec_10_18.txt')

In [22]:
for i, j in ((1,2), (3,4), (5,6), (7,8)):
    print('vectors with indeces:', i, j)
    i_proj_i = np.dot(ei_vec[:,i], fr[:, i])
    i_proj_j = np.dot(ei_vec[:,i], fr[:, j])
    j_proj_i = np.dot(ei_vec[:,j], fr[:, i])
    j_proj_j = np.dot(ei_vec[:,j], fr[:, j])
    print(i_proj_i, i_proj_j, j_proj_i, j_proj_j)
    print('\tsums of squares:', i_proj_i ** 2 + i_proj_j  ** 2, j_proj_i ** 2 + j_proj_j  ** 2)
    print('\tDot product between i and j:', np.dot(ei_vec[:,i], ei_vec[:, j]))
    print('\tDot product between i and j in fr:', np.dot(fr[:,i], fr[:, j]))

vectors with indeces: 1 2
-0.4039706251354577 0.9147711638063419 -0.8945505873693391 -0.4469651959772277
	sums of squares: 0.9999985481039417 0.9999986397777911
	Dot product between i and j: -0.047499151907367934
	Dot product between i and j in fr: -2.0282399998405864e-07
vectors with indeces: 3 4
0.3664891527221191 -0.9304227066508538 -0.9132220678515395 -0.40746257796626434
	sums of squares: 1.0000007121144776 1.0000002976539557
	Dot product between i and j: 0.04442704210688851
	Dot product between i and j in fr: -5.773760000243877e-07
vectors with indeces: 5 6
0.98286237087748 0.1843409200006014 -0.24189464670341743 0.9703025006707027
	sums of squares: 1.000000014873569 0.9999999629115901
	Dot product between i and j: -0.0588830586875494
	Dot product between i and j in fr: 3.4629799997715205e-07
vectors with indeces: 7 8
0.8631794649343396 0.5048972205578104 -0.6022227863097909 0.798327958460435
	sums of squares: 0.9999999920113352 0.9999998136103341
	Dot product between i and j: -0

It looks like eigenvectors with multiplicity >= 2 are not orthogonal (dot product is much higher than in fr and is
in same order of magnitude as numeric error of 1RDM)
Google said that if we want to make vectors orthogonal we should use
https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process

In [24]:
ei_vec_orth = ei_vec
for i, j in ((1,2), (3,4), (5,6), (7,8)):
    ei_vec[:, j] = ei_vec[:, j] - ei_vec[:, i] * (np.dot(ei_vec[:, j],ei_vec[:, i])/np.dot(ei_vec[:, i],ei_vec[:, i]))
    print(i_proj_i, i_proj_j, j_proj_i, j_proj_j)
    print('\tsums of squares:', i_proj_i ** 2 + i_proj_j  ** 2, j_proj_i ** 2 + j_proj_j  ** 2)
    print('\tDot product between i and j:', np.dot(ei_vec[:,i], ei_vec[:, j]))
    print('\tDot product between i and j in fr:', np.dot(fr[:,i], fr[:, j]))

0.8631794649343396 0.5048972205578104 -0.6022227863097909 0.798327958460435
	sums of squares: 0.9999999920113352 0.9999998136103341
	Dot product between i and j: 0.0
	Dot product between i and j in fr: -2.0282399998405864e-07
0.8631794649343396 0.5048972205578104 -0.6022227863097909 0.798327958460435
	sums of squares: 0.9999999920113352 0.9999998136103341
	Dot product between i and j: 6.938893903907228e-18
	Dot product between i and j in fr: -5.773760000243877e-07
0.8631794649343396 0.5048972205578104 -0.6022227863097909 0.798327958460435
	sums of squares: 0.9999999920113352 0.9999998136103341
	Dot product between i and j: 4.85722573273506e-17
	Dot product between i and j in fr: 3.4629799997715205e-07
0.8631794649343396 0.5048972205578104 -0.6022227863097909 0.798327958460435
	sums of squares: 0.9999999920113352 0.9999998136103341
	Dot product between i and j: 1.3877787807814457e-17
	Dot product between i and j in fr: 1.9562400000588953e-07


In [29]:
print_matrix(calculate_gamma(ei_vec_orth))
print_matrix(calculate_gamma(ei_vec))
print_matrix(calculate_gamma(fr))

0 0 0 0.0 0.10000000000000028
1 0 0 0.10000000000000028 0.0004512338863838408
2 0 0 0.10045123388638412 0.1990985502873339
3 0 0 0.299549784173718 0.20000000000000018
4 0 0 0.4995497841737182 2.2256527919824994e-32
5 0 0 0.4995497841737182 0.08654560035200196
6 0 0 0.5860953845257202 0.11306102889705891
7 0 0 0.6991564134227791 0.19999999999999993
8 0 0 0.8991564134227791 6.741989326449678e-28
   +0.899156     +0.100071     -0.100043     +0.099599     -0.099443     +0.100844     -0.100071     +0.100043     -0.099599     +0.099443
   +0.100071     +0.897875     +0.101037     -0.100611     +0.101359     -0.100071     +0.099527     -0.098431     +0.098004     -0.098762
   -0.100043     +0.101037     +0.897307     +0.102798     -0.101239     +0.100043     -0.098431     +0.097489     -0.097594     +0.098633
   +0.099599     -0.100611     +0.102798     +0.896678     +0.101482     -0.099599     +0.098004     -0.097594     +0.098117     -0.098875
   -0.099443     +0.101359     -0.101239     +0

In [31]:
from sympy import Matrix
M = Matrix(obj.h)
eig = M.eigenvects()

In [40]:
ei_vec_matrix = []
ei_val_matrix = []
for eigenval, multiplicity, vectors in eig:
    print(f'Eigenvalue {eigenval.evalf()} ({eigenval}), multiplicity {multiplicity}')
    ei_vec_matrix.append(list(vectors[0]))
    ei_val_matrix.append(eigenval)

ei_vec_matrix = np.array(ei_vec_matrix).T
ei_val_matrix = np.array(ei_val_matrix)
idx = ei_val_matrix.argsort()[::1] # Sorting matrix and vector by ascending order
ei_val_matrix = ei_val_matrix[idx]
ei_vec_matrix = ei_vec_matrix[:, idx]

print(ei_vec_matrix)

Eigenvalue -1.61803398874989 (-1.61803398874989), multiplicity 1
Eigenvalue -2.00000000000000 (-2.00000000000000), multiplicity 1
Eigenvalue -1.61803398874989 (-1.61803398874989), multiplicity 1
Eigenvalue -0.618033988749895 (-0.618033988749895), multiplicity 1
Eigenvalue -0.618033988749895 (-0.618033988749895), multiplicity 1
Eigenvalue 0.618033988749895 (0.618033988749895), multiplicity 1
Eigenvalue 0.618033988749895 (0.618033988749895), multiplicity 1
Eigenvalue 2.00000000000000 (2.00000000000000), multiplicity 1
Eigenvalue 1.61803398874989 (1.61803398874989), multiplicity 1
Eigenvalue 1.61803398874989 (1.61803398874989), multiplicity 1
[[0.316227766016838 -0.226872476432246 0.380676528946908
  0.435677176675977 0.109824789148093 0.446800296777347
  -0.108582306874277 -0.398187002967935 0.203585634727535
  -0.316227766016838]
 [0.316227766016838 -0.410072860991640 0.169910707042699
  0.230614873043513 -0.378454695999007 -0.156350328556571
  -0.387722266867997 0.441804686011735 0.069

In [42]:
print_matrix(calculate_gamma(ei_vec_matrix))

0 0 0 0.0 0.100000000000000
1 0 0 0.1 0.0514711205624999
2 0 0 0.15147112056249987 0.144914619691066
3 0 0 0.2963857402535662 0.189814602276350
4 0 0 0.4862003425299166 0.0120614843114231
5 0 0 0.49826182684133974 0.199630505200326
6 0 0 0.6978923320416655 0.0117901173661397
7 0 0 0.7096824494078051 0.158552889332587
8 0 0 0.8682353387403917 0.0414471106674134
   +0.909682     +0.127064     -0.139127     +0.085879     -0.053083     +0.094070     -0.132851     +0.131798     -0.084621     +0.061189
   +0.127064     +0.868215     +0.081502     -0.057554     +0.101260     -0.132851     +0.124608     -0.080151     +0.065566     -0.097659
   -0.139127     +0.081502     +0.949788     +0.096883     -0.137322     +0.131798     -0.080151     +0.058376     -0.093189     +0.131441
   +0.085879     -0.057554     +0.096883     +0.870020     +0.127421     -0.084621     +0.065566     -0.093189     +0.124251     -0.134656
   -0.053083     +0.101260     -0.137322     +0.127421     +0.922720     +0.06118

# I GAVE UP!!!!
trying to transform and calculate eigenvectors with lapack!

In [47]:
conn = open('temp_size.dat', 'w')
conn.write(str(int(obj.h.shape[0])))
conn.close()
np.savetxt('temp_matrix.dat', obj.h)

In [48]:
obj.h.shape[0]
import subprocess
import os
if not os.path.isfile('calculate_eigenvectors.exe'):
    subprocess.run(['gfortran', 'Calculate_eigenvectors.f90', 'diagmat.f90', 'liblapack.dll', 'libblas.dll', '-o',
                    'calculate_eigenvectors'])
subprocess.run(['calculate_eigenvectors.exe'])

CompletedProcess(args=['calculate_eigenvectors.exe'], returncode=0)

In [49]:
ei_vec = np.loadtxt('temp_ei_vec.dat')
ei_val = np.loadtxt('temp_ei_val.dat')

print_matrix(calculate_gamma(ei_vec))


0 0 0 0.0 0.10000000000000007
1 0 0 0.10000000000000007 0.16004439950817828
2 0 0 0.26004439950817837 0.039955600491821675
3 0 0 0.30000000000000004 0.026862820654239266
4 0 0 0.3268628206542393 0.17313717934576076
5 0 0 0.5000000000000001 0.12336683612647512
6 0 0 0.6233668361264753 0.07663316387352487
7 0 0 0.7000000000000002 0.14901585658668973
8 0 0 0.8490158565866899 0.05098414341331023
   +0.900000     +0.100000     -0.100000     +0.100000     -0.100000     +0.100000     -0.100000     +0.100000     -0.100000     +0.100000
   +0.100000     +0.900000     +0.100000     -0.100000     +0.100000     -0.100000     +0.100000     -0.100000     +0.100000     -0.100000
   -0.100000     +0.100000     +0.900000     +0.100000     -0.100000     +0.100000     -0.100000     +0.100000     -0.100000     +0.100000
   +0.100000     -0.100000     +0.100000     +0.900000     +0.100000     -0.100000     +0.100000     -0.100000     +0.100000     -0.100000
   -0.100000     +0.100000     -0.100000     +0.1